- name: Install Docker
  dnf:
    name: docker
    state: present

- name: Make sure Docker is running
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes

- name: Add user 'fedora' to group 'docker'
  user: name=fedora groups=docker append=yes